"""Small Jira webhook server used by the investigation demo.

The HTTP and queue plumbing lives here so agentic_lr_investigation.py can stay
focused on investigating tickets. The in-memory queue is an intentional demo
tradeoff: accepted work is lost if the process stops before it is handled.
"""

import asyncio
from copy import deepcopy
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
import hashlib
import hmac
import json
import logging
import os

from fastapi import FastAPI, Header, HTTPException, Request, Response, status
from pydantic import BaseModel, ConfigDict, Field
import uvicorn


logger = logging.getLogger(__name__)

IssueHandler = Callable[[str], Awaitable[None]]


class InvestigationRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    issue_id: str = Field(pattern=r"^(?:[A-Z][A-Z0-9_]*-[1-9][0-9]*|[1-9][0-9]*)$", max_length=100)


def request_log_config() -> dict:
    """Timestamp Uvicorn lifecycle and access logs, including health checks."""
    config = deepcopy(uvicorn.config.LOGGING_CONFIG)
    for formatter in config["formatters"].values():
        formatter["fmt"] = "%(asctime)s %(levelname)s %(name)s: %(message)s"
        formatter["use_colors"] = False
    return config


@dataclass(frozen=True)
class JiraWebhookConfig:
    secret: str
    host: str = "127.0.0.1"
    port: int = 8080

    @classmethod
    def from_environment(cls, require_secret: bool = True) -> "JiraWebhookConfig":
        secret = os.environ.get("JIRA_WEBHOOK_SECRET", "")
        if require_secret and not secret:
            raise RuntimeError(
                "JIRA_WEBHOOK_SECRET must be set when JIRA_TRIGGER_MODE=webhook"
            )

        return cls(
            secret=secret,
            host=os.environ.get("JIRA_WEBHOOK_HOST", "127.0.0.1"),
            port=int(os.environ.get("JIRA_WEBHOOK_PORT", "8080")),
        )


def signature_is_valid(body: bytes, signature: str | None, secret: str) -> bool:
    """Validate the sha256 signature generated by a Jira admin webhook."""
    if not signature:
        return False

    method, separator, supplied_digest = signature.partition("=")
    if separator != "=" or method.lower() != "sha256" or not supplied_digest:
        return False

    expected_digest = hmac.new(
        secret.encode("utf-8"),
        body,
        hashlib.sha256,
    ).hexdigest()
    return hmac.compare_digest(supplied_digest.lower(), expected_digest)


def create_webhook_app(
    queue: asyncio.Queue[str],
    secret: str,
) -> FastAPI:
    """Create the HTTP app separately so it can be tested without a server."""
    app = FastAPI(
        title="Jira Lightrun investigation demo",
        docs_url=None,
        redoc_url=None,
    )
    seen_deliveries: set[str] = set()

    @app.get("/health/live")
    async def live() -> dict[str, str]:
        return {"status": "ok"}

    @app.post("/investigations", status_code=status.HTTP_202_ACCEPTED)
    async def investigate(payload: InvestigationRequest) -> dict[str, str]:
        # Deliberately unauthenticated for this demo. Reuse the bounded worker
        # queue; Jira lookup and eligibility checks happen asynchronously.
        try:
            queue.put_nowait(payload.issue_id)
        except asyncio.QueueFull:
            raise HTTPException(status_code=503, detail="Investigation queue is full") from None
        logger.info("Accepted manual investigation for Jira issue %s", payload.issue_id)
        return {"status": "queued", "issue_id": payload.issue_id}

    @app.post("/webhooks/jira", status_code=status.HTTP_202_ACCEPTED)
    async def jira_webhook(
        request: Request,
        x_hub_signature: str | None = Header(default=None),
        x_atlassian_webhook_identifier: str | None = Header(default=None),
    ) -> Response:
        if not secret:
            raise HTTPException(status_code=503, detail="Jira webhook is not configured")
        body = await request.body()
        if not signature_is_valid(body, x_hub_signature, secret):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid Jira webhook signature",
            )

        try:
            payload = json.loads(body)
            event = payload["webhookEvent"]
            issue_key = payload["issue"]["key"]
        except (json.JSONDecodeError, KeyError, TypeError):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Invalid Jira webhook payload",
            ) from None

        if event != "jira:issue_created":
            return Response(status_code=status.HTTP_204_NO_CONTENT)

        # Jira keeps this identifier stable when it retries a delivery.
        if (
            x_atlassian_webhook_identifier
            and x_atlassian_webhook_identifier in seen_deliveries
        ):
            return Response(status_code=status.HTTP_204_NO_CONTENT)

        try:
            queue.put_nowait(issue_key)
        except asyncio.QueueFull:
            # A retryable response asks Jira to deliver the event again.
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="Investigation queue is full",
            ) from None

        if x_atlassian_webhook_identifier:
            seen_deliveries.add(x_atlassian_webhook_identifier)

        logger.info("Accepted Jira webhook for issue %s", issue_key)
        return Response(status_code=status.HTTP_202_ACCEPTED)

    return app


async def _consume_issues(
    queue: asyncio.Queue[str],
    handle_issue: IssueHandler,
) -> None:
    while True:
        issue_key = await queue.get()
        try:
            await handle_issue(issue_key)
        except Exception:
            # Ticket processing records its own Jira failure comment and label.
            # Keep the demo worker alive so the next ticket can still run.
            logger.exception("Webhook worker failed for Jira issue %s", issue_key)
        finally:
            queue.task_done()


async def run_jira_webhook_service(
    handle_issue: IssueHandler,
    config: JiraWebhookConfig,
) -> None:
    """Run one HTTP receiver and one ticket worker until shutdown."""
    queue: asyncio.Queue[str] = asyncio.Queue(maxsize=100)
    app = create_webhook_app(queue, config.secret)
    server = uvicorn.Server(
        uvicorn.Config(
            app,
            host=config.host,
            port=config.port,
            log_level="info",
            log_config=request_log_config(),
        )
    )

    logger.info(
        "Listening for Jira webhooks on http://%s:%d/webhooks/jira",
        config.host,
        config.port,
    )
    logger.info("Manual investigation endpoint: POST http://%s:%d/investigations (unauthenticated)",
                config.host, config.port)
    server_task = asyncio.create_task(server.serve())
    worker_task = asyncio.create_task(_consume_issues(queue, handle_issue))

    done, pending = await asyncio.wait(
        {server_task, worker_task},
        return_when=asyncio.FIRST_COMPLETED,
    )
    for task in pending:
        task.cancel()
    await asyncio.gather(*pending, return_exceptions=True)

    for task in done:
        task.result()
